version: "3.8"

services:
  astronaut-api:
    build:
      context: ./nestjs-backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_HOST=astronaut-db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=nestjs_db
      - FRONT_END_HOST=http://localhost:3000
      - MIGRATION_PATH=src/migrations/**/*{.ts,.js}
    depends_on:
      astronaut-db:
        condition: service_healthy
    volumes:
      - ./nestjs-backend/src:/app/src

  astronaut-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  astronaut-admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      astronaut-db:
        condition: service_healthy

  front-eleven-test:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/
      - /app/node_modules
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  pgadmin_data: